import { afterEach, expect, it, vi } from "vitest";
import type { MobileAuthController } from "../auth/mobile-auth";
import type { MobileAuthState } from "../auth/state-machine";
import { bindSavedTakeAudioMemory } from "./saved-take-memory-lifecycle";
import { SavedTakeAudioMemory } from "./saved-take-memory";
afterEach(() => vi.unstubAllGlobals());
it("wires native inactive, visibility, offline, session, logout and late listener cleanup", async () => {
  const doc = Object.assign(new EventTarget(), { visibilityState: "visible" });
  const win = new EventTarget(), nav = { onLine: true };
  vi.stubGlobal("document", doc); vi.stubGlobal("window", win); vi.stubGlobal("navigator", nav);
  let publish!: (state: MobileAuthState) => void;
  let native!: (active: boolean) => void;
  let resolve!: (handle: { remove: () => Promise<void> }) => void;
  const unsubscribe = vi.fn(), remove = vi.fn(async () => undefined);
  const auth = { subscribe: (listener: typeof publish) => { publish = listener; return unsubscribe; } } as unknown as MobileAuthController;
  const memory = new SavedTakeAudioMemory(() => true), invalidate = vi.fn();
  const off = memory.subscribe(invalidate);
  const stop = bindSavedTakeAudioMemory(memory, auth, "a", listener => { native = listener; return new Promise(r => { resolve = r; }); });
  const visit = memory.beginVisit("s", "t");
  native(false); expect(memory.current(visit)).toBe(false);
  doc.dispatchEvent(new Event("visibilitychange")); expect(memory.current(visit)).toBe(false);
  native(true); expect(memory.current(visit)).toBe(true);
  doc.visibilityState = "hidden"; doc.dispatchEvent(new Event("visibilitychange")); expect(memory.current(visit)).toBe(false);
  doc.visibilityState = "visible"; doc.dispatchEvent(new Event("visibilitychange"));
  nav.onLine = false; win.dispatchEvent(new Event("offline")); expect(memory.current(visit)).toBe(false);
  nav.onLine = true; win.dispatchEvent(new Event("online"));
  const n = invalidate.mock.calls.length; publish({ kind: "refreshing" }); publish({ kind: "authenticated", userId: "a" }); expect(invalidate).toHaveBeenCalledTimes(n + 2);
  publish({ kind: "authenticated", userId: "b" }); publish({ kind: "authenticated", userId: "a" }); expect(memory.current(visit)).toBe(false);
  publish({ kind: "signing_out" }); stop(); off(); resolve({ remove }); await Promise.resolve();
  expect(remove).toHaveBeenCalledOnce(); expect(unsubscribe).toHaveBeenCalledOnce();
  const count = invalidate.mock.calls.length; doc.dispatchEvent(new Event("visibilitychange")); win.dispatchEvent(new Event("offline")); native(true); expect(invalidate).toHaveBeenCalledTimes(count);
});
